### ISSUE TITLE
After the broadcast Notification of no completion of broadcast 

### ISSUE THREAD

**Issue by mrdong916** [danielR2001/flutter_exoplayer#27]
播放完成后收不到完成的通知
After the broadcast Notification of no completion of broadcast 
```
 // 监听是否播放完成事件
    _playerCompleteSubscription =
        audioPlayer.onPlayerCompletion.listen((event) {
      print("complete");
    });
```

请问我的播放列表不是一个播放地址集合，而是ID的集合，然后通过ID获取播放地址，我应该如何处理
Please ask my playlist is not a collection of playback addresses, but a collection of IDs, and then get the playback address through the ID, how should I handle it

**Comment by danielR2001** [comment]
Hello, I'm getting a hard time understanding you but as far as I understand Your problem is that you don't receive 'onPlayerCompletion' notification, I will look into that.  For the second question, I think you need to obtain all the addresses before playing the playlist OR play first address and in background load all of the other addresses and then play as playlist.

**Comment by mrdong916** [comment]
Sorry, my English is terrible, it ’s all translated by translation software

Regarding the second question, if you add many songs to my application for play at one time, you need to get the play address of many music at once. In this case, resources will be wasted. In fact, this situation can be avoided. I think the playlist should give a collection of objects, and then specify the properties of the objects in the collection as the play address, and give a callback when switching music to get the play address.

Thank you

**Comment by danielR2001** [comment]
There is a problem with your way because I use Exoplayer's `concatenatingmediasource` when using playlists, that gets an array of play addresses, so the playlist can't be initiated without all the addresses at once.
