### ISSUE TITLE
Releasing the player

### ISSUE THREAD

**Issue by rodrigo-martins-ifood** [danielR2001/flutter_exoplayer#45]
Hi, how is going? I have an problem with my app and i did the test also on the project of example and happens the same error.

If you start to play some audio (Android device) and press the back button (the right arrow on the navigation bar) the app will be killed but the audio keeps playing, and when you open the app again the audio is still running but you can't recover the status of the playing audio. I'm trying to kill the player on onStop or onDestroy but the release, dispose or stop does not work. And i am also trying to recover some data to stop the audio or in the best case load again the seek bar and keep the thinks rolling.

And the second think is there is any plan for impl the audio media buttons? I did see the comment on the code telling to impl haha. 

Thanks a lot.

**Comment by danielR2001** [comment]
thank you for pointing this out, I'm looking into it now.

**Comment by danielR2001** [comment]
ok, the problem isn't in the library, it's in the way you build your project, the test program was built slopy (sorry for this), I didn't build separate class of the audio player. So the problem is when you press back button and then enter the app again my library works fine but the main page reloads all the pages and calls initState function that initiates the audio player without destroying it first.

**Comment by rodrigo-martins-ifood** [comment]
Yeah like i said, if you test your example application happens the same problem, start playing something press the back button, and when you open the app again you can't stop the audio that is playing, only if you close the app literally.  And when this happen you can't do nothing because the library doesn't recognise the mediaContext anymore, and this is killing me right know.
